import type { EnemyType } from "@/types/game";
import { AREA_LIVE_CAP, AREA_TOTAL_ENEMIES } from "@config/area";

// The three starting biomes. For now a biome is only a background colour and a
// creature pool — points of interest, treasure and dungeons come later, as does
// the dedicated portal travel screen that replaces the temporary picker.
export type BiomeId = "forest" | "desert" | "tundra";

export interface BiomeDefinition {
    id: BiomeId;
    // Player-facing name, used by the biome picker and the HUD.
    name: string;
    // Applied per-scene via `cameras.main.setBackgroundColor`, so the global
    // `backgroundColor` in PhaserGame.tsx (and therefore the town) is untouched.
    backgroundColor: string;
    // Creatures that spawn here, and the pool the boss is promoted from.
    enemies: EnemyType[];
    // Tilemap for the area, generated by `scripts/generate-biome-maps.mjs`.
    map: BiomeMap;
    // Total enemies to clear before the boss, and how many may be alive at once.
    total: number;
    liveCap: number;
}

/**
 * How a biome's .tmj hangs together. `key` is the tilemap cache key from
 * LoadScene; each `tilesets` entry pairs the tileset name *inside* the .tmj with
 * the image key the same scene preloaded under.
 *
 * The three sheets are identical in layout across the biomes (the fantasy_ pack
 * ships them that way), so `biomeMap` derives the whole thing from the id and
 * the only per-biome difference is the palette.
 */
export interface BiomeMap {
    key: string;
    tilesets: { name: string; image: string }[];
    // Bottom to top. Every biome .tmj carries these five, and the generator
    // writes them in this order.
    layers: string[];
    // Layers whose tiles can carry `collides: true`. The rest are decoration.
    collisionLayers: string[];
    // Layers holding the upper half of a standing prop — canopies, boulder tops.
    // These draw beneath the characters like every other layer, and BiomeScene
    // additionally redraws the few tiles near a character as individually
    // depth-sorted sprites, so walking up behind a tree puts its canopy in
    // front of you. See `BiomeScene.updatePropOverlays`.
    propLayers: string[];
    // Spritesheet key for those overlay sprites: the same art as the layer's
    // tileset, loaded with frames so a tile index can be drawn on its own.
    propsTexture: string;
    // Tile art is 16px; the town renders its map at 2x and the biomes match, so
    // the player reads at the same size in both.
    scale: number;
}

function biomeMap(id: BiomeId): BiomeMap {
    return {
        key: `${id}-map`,
        tilesets: [
            { name: `${id}_`, image: `${id}Terrain` },
            { name: `${id}Path_`, image: `${id}Path` },
            { name: `${id}_ [resources]`, image: `${id}Resources` },
        ],
        layers: ["terrain", "terrain props", "paths", "structure", "structure props"],
        collisionLayers: ["terrain", "structure"],
        propLayers: ["structure props"],
        propsTexture: `${id}Props`,
        scale: 2,
    };
}

// Difficulty tiers, overlapping at the edges so the ramp between biomes is a
// slope rather than a step: the forest is the starter, the tundra the hardest.
// `total`/`liveCap` are identical across the three for now — they live on the
// definition so per-biome tuning is a config edit rather than a refactor.
export const BIOMES: Record<BiomeId, BiomeDefinition> = {
    forest: {
        id: "forest",
        map: biomeMap("forest"),
        name: "Forest",
        backgroundColor: "#4a7c3f",
        enemies: ["baby-ghoul", "skeleton", "ghoul", "imp"],
        total: AREA_TOTAL_ENEMIES,
        liveCap: AREA_LIVE_CAP,
    },
    desert: {
        id: "desert",
        map: biomeMap("desert"),
        name: "Desert",
        backgroundColor: "#d9c06a",
        enemies: ["imp", "ghoul", "satyr", "egbert"],
        total: AREA_TOTAL_ENEMIES,
        liveCap: AREA_LIVE_CAP,
    },
    tundra: {
        id: "tundra",
        map: biomeMap("tundra"),
        name: "Tundra",
        backgroundColor: "#e8eef2",
        enemies: ["satyr", "egbert", "slime"],
        total: AREA_TOTAL_ENEMIES,
        liveCap: AREA_LIVE_CAP,
    },
};

export const DEFAULT_BIOME: BiomeId = "forest";

export const BIOME_IDS = Object.keys(BIOMES) as BiomeId[];

// Narrows an unknown/absent id to a real biome, falling back to the default
// rather than throwing — a bad id should drop the player somewhere playable.
// Takes a plain string so callers carrying an unvalidated value (a travel
// request off the store, a persisted id) can pass it without a cast.
export function resolveBiome(id?: string | null): BiomeDefinition {
    return (id && BIOMES[id as BiomeId]) || BIOMES[DEFAULT_BIOME];
}
